version: '3'

services:
  app:
    image: dart:stable
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "dart pub get && tail -f /dev/null"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: applications
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"