name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Test
        run: dart test